version: "3.9"
services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0 
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh /etc/kafka/config/zookeeper.properties"
      ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    volumes:
      - ./config:/etc/kafka/config

  kafka:
    image: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh /etc/kafka/config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      CLASSPATH: "/usr/share/kafka/libs/kafka-audit-authorizer-1.0-SNAPSHOT.jar"
    volumes:
      - ./config:/etc/kafka/config
      - ./kafka-audit-authorizer/target:/usr/share/kafka/libs
